esphome:
 name: light
 
esp8266:
 board: d1_mini
 
# Enable logging
logger:
 
# Enable Home Assistant API
api:
 encryption:
   key: <GENERATED_ENCRYPTION_KEY>
 
ota:
 password: <PASSWORD>
 
wifi:
 ssid: !secret wifi_ssid
 password: !secret wifi_password
 
 # Enable fallback hotspot (captive portal) in case wifi connection fails
 ap:
   ssid: "Light Fallback Hotspot"
   password: <PASSWORD>
 
captive_portal:
 
light:
 - platform: binary
   name: "red"
   output: red
 
 - platform: binary
   name: "yellow"
   output: yellow
 
 - platform: binary
   name: "green"
   output: green
 
 - platform: binary
   name: "blue"
   output: blue
 
output:
 - id: red
   platform: gpio
   pin: D6
  - id: yellow
   platform: gpio
   pin: D5
 
 - id: green
   platform: gpio
   pin: D0
 
 - id: blue
   platform: gpio
   pin: D7
