esphome:
 name: magnet
 
esp8266:
 board: d1_mini
 
# Enable logging
logger:
 
# Enable Home Assistant API
api:
 encryption:
   key: <GENERATED_ENCRYPTION_KEY>
 
ota:
 password: <PASSWORD>
 
wifi:
 ssid: !secret wifi_ssid
 password: !secret wifi_password
 
 # Enable fallback hotspot (captive portal) in case wifi connection fails
 ap:
   ssid: "Magnet Fallback Hotspot"
   password: <PASSWORD>
 
captive_portal:
 
binary_sensor:
 - platform: gpio
   pin:
     number: D4
     mode: INPUT_PULLUP
   name: "Door Sensor"
   device_class: garage_door
